
networks:
  # Usar a rede do Traefik existente
  traefik_network:
    external: true
    name: n8nhub_traefik_network
  # Rede interna para comunicação entre serviços
  workadventure_internal:
    driver: bridge

services:
  play:
    image: thecodingmachine/workadventure-play:${VERSION}
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - JITSI_URL=${JITSI_URL:-meet.jit.si}
      - JITSI_PRIVATE_MODE=${JITSI_PRIVATE_MODE:-false}
      - ENABLE_MAP_EDITOR=${ENABLE_MAP_EDITOR:-true}
      - MAP_EDITOR_ALLOWED_USERS=${MAP_EDITOR_ALLOWED_USERS:-}
      - MAP_EDITOR_ALLOW_ALL_USERS=${MAP_EDITOR_ALLOW_ALL_USERS:-true}
      - PUSHER_URL=https://${DOMAIN}/
      - ICON_URL=/icon
      - TURN_SERVER=${TURN_SERVER:-}
      - TURN_USER=${TURN_USER:-}
      - TURN_PASSWORD=${TURN_PASSWORD:-}
      - TURN_STATIC_AUTH_SECRET=${TURN_STATIC_AUTH_SECRET:-}
      - STUN_SERVER=${STUN_SERVER:-stun:stun.l.google.com:19302}
      - SKIP_RENDER_OPTIMIZATIONS=${SKIP_RENDER_OPTIMIZATIONS:-false}
      - MAX_PER_GROUP=${MAX_PER_GROUP:-10}
      - MAX_USERNAME_LENGTH=${MAX_USERNAME_LENGTH:-25}
      - DISABLE_ANONYMOUS=${DISABLE_ANONYMOUS:-true}
      - DISABLE_NOTIFICATIONS=${DISABLE_NOTIFICATIONS:-false}
      - SECRET_KEY=${SECRET_KEY}
      - API_URL=back:50051
      - FRONT_URL=/
      - INTERNAL_MAP_STORAGE_URL=http://map-storage:3000
      - PUBLIC_MAP_STORAGE_URL=https://${DOMAIN}/map-storage
      - START_ROOM_URL=${START_ROOM_URL}
      - OPID_PROMPT=login
      - OPID_WOKA_NAME_POLICY=${OPID_WOKA_NAME_POLICY:-user_input}
      - OPID_CLIENT_ID=${OPID_CLIENT_ID:-}
      - OPID_CLIENT_SECRET=${OPID_CLIENT_SECRET:-}
      - OPID_CLIENT_ISSUER=${OPID_CLIENT_ISSUER:-}
      - OPID_PROFILE_SCREEN_PROVIDER=${OPID_PROFILE_SCREEN_PROVIDER:-}
      - OPID_SCOPE=${OPID_SCOPE:-}
      - OPID_USERNAME_CLAIM=${OPID_USERNAME_CLAIM:-}
      - OPID_LOCALE_CLAIM=${OPID_LOCALE_CLAIM:-}
      - OPID_LOGOUT_REDIRECT_URL=${OPID_LOGOUT_REDIRECT_URL:-}
      - FALLBACK_LOCALE=${FALLBACK_LOCALE:-pt-BR}
      - ENABLE_CHAT=${ENABLE_CHAT:-true}
      - ENABLE_CHAT_UPLOAD=${ENABLE_CHAT_UPLOAD:-true}
      - ENABLE_CHAT_ONLINE_LIST=${ENABLE_CHAT_ONLINE_LIST:-true}
      - ENABLE_CHAT_DISCONNECTED_LIST=${ENABLE_CHAT_DISCONNECTED_LIST:-true}
      - UPLOADER_URL=/uploader
      - ENABLE_REPORT_ISSUES_MENU=${ENABLE_REPORT_ISSUES_MENU:-false}
      - REPORT_ISSUES_URL=${REPORT_ISSUES_URL:-}
      - ENABLE_OPENAPI_ENDPOINT=true
      - ADMIN_API_TOKEN=${ADMIN_API_TOKEN:-}
      - ADMIN_API_URL=${ADMIN_API_URL:-}
      - ADMIN_URL=${ADMIN_URL:-}
      - ROOM_API_PORT=50051
      - ROOM_API_SECRET_KEY=${ROOM_API_SECRET_KEY}
      - GRPC_VERBOSITY=ERROR
      - GRPC_TRACE=all
      - SENTRY_ORG=${SENTRY_ORG:-}
      - SENTRY_PROJECT=${SENTRY_PROJECT:-}
      - SENTRY_DSN_FRONT=${SENTRY_DSN_FRONT:-}
      - SENTRY_DSN_PUSHER=${SENTRY_DSN_PUSHER:-}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-}
      - SENTRY_RELEASE=${SENTRY_RELEASE:-}
      - SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-}
      - JITSI_DOMAIN=${JITSI_DOMAIN:-}
      - JITSI_XMPP_DOMAIN=${JITSI_XMPP_DOMAIN:-}
      - JITSI_MUC_DOMAIN=${JITSI_MUC_DOMAIN:-}
      - WOKA_SPEED=${WOKA_SPEED:-}
      - FEATURE_FLAG_BROADCAST_AREAS=${FEATURE_FLAG_BROADCAST_AREAS:-}
      - KLAXOON_ENABLED=${KLAXOON_ENABLED:-false}
      - KLAXOON_CLIENT_ID=${KLAXOON_CLIENT_ID:-}
      - YOUTUBE_ENABLED=${YOUTUBE_ENABLED:-true}
      - GOOGLE_DRIVE_ENABLED=${GOOGLE_DRIVE_ENABLED:-true}
      - GOOGLE_DOCS_ENABLED=${GOOGLE_DOCS_ENABLED:-true}
      - GOOGLE_SHEETS_ENABLED=${GOOGLE_SHEETS_ENABLED:-true}
      - GOOGLE_SLIDES_ENABLED=${GOOGLE_SLIDES_ENABLED:-true}
      - ERASER_ENABLED=${ERASER_ENABLED:-true}
      - EXCALIDRAW_ENABLED=${EXCALIDRAW_ENABLED:-true}
      - EXCALIDRAW_DOMAINS=${EXCALIDRAW_DOMAINS:-excalidraw.com}
      - EMBEDDED_DOMAINS_WHITELIST=${EMBEDDED_DOMAINS_WHITELIST:-youtube.com}
      - CARDS_ENABLED=${CARDS_ENABLED:-true}
      - PEER_VIDEO_LOW_BANDWIDTH=${PEER_VIDEO_LOW_BANDWIDTH:-150}
      - PEER_VIDEO_RECOMMENDED_BANDWIDTH=${PEER_VIDEO_RECOMMENDED_BANDWIDTH:-600}
      - PEER_SCREEN_SHARE_LOW_BANDWIDTH=${PEER_SCREEN_SHARE_LOW_BANDWIDTH:-250}
      - PEER_SCREEN_SHARE_RECOMMENDED_BANDWIDTH=${PEER_SCREEN_SHARE_RECOMMENDED_BANDWIDTH:-1000}
      - GOOGLE_DRIVE_PICKER_CLIENT_ID=${GOOGLE_DRIVE_PICKER_CLIENT_ID:-}
      - GOOGLE_DRIVE_PICKER_APP_ID=${GOOGLE_DRIVE_PICKER_APP_ID:-}
      - MAP_STORAGE_API_TOKEN=${MAP_STORAGE_API_TOKEN:-${SECRET_KEY}}
      - MATRIX_API_URI=${MATRIX_API_URI:-}
      - MATRIX_PUBLIC_URI=${MATRIX_PUBLIC_URI:-}
      - MATRIX_ADMIN_USER=${MATRIX_ADMIN_USER:-}
      - MATRIX_ADMIN_PASSWORD=${MATRIX_ADMIN_PASSWORD:-}
      - MATRIX_DOMAIN=${MATRIX_DOMAIN:-}
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_MOTD=${SERVER_MOTD}
      - SERVER_ICON=${SERVER_ICON}
      - BRANDING_LOGO_URL=${BRANDING_LOGO_URL}
    networks:
      - traefik_network
      - workadventure_internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8nhub_traefik_network"
      
      # Rota principal
      - "traefik.http.routers.workadventure-play.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.workadventure-play.entrypoints=websecure"
      - "traefik.http.routers.workadventure-play.tls=true"
      - "traefik.http.routers.workadventure-play.tls.certresolver=myresolver"
      - "traefik.http.routers.workadventure-play.service=workadventure-play"
      - "traefik.http.services.workadventure-play.loadbalancer.server.port=3000"

      # WebSocket
      - "traefik.http.routers.workadventure-play-ws.rule=Host(`${DOMAIN}`) && PathPrefix(`/ws/`)"
      - "traefik.http.routers.workadventure-play-ws.entrypoints=websecure"
      - "traefik.http.routers.workadventure-play-ws.tls=true"
      - "traefik.http.routers.workadventure-play-ws.tls.certresolver=myresolver"
      - "traefik.http.routers.workadventure-play-ws.service=workadventure-play-ws"
      - "traefik.http.services.workadventure-play-ws.loadbalancer.server.port=3001"

      # Room API gRPC
      - "traefik.http.routers.workadventure-room-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.workadventure-room-api.entrypoints=grpc"
      - "traefik.http.routers.workadventure-room-api.service=workadventure-room-api"
      - "traefik.http.services.workadventure-room-api.loadbalancer.server.port=50051"
      - "traefik.http.services.workadventure-room-api.loadbalancer.server.scheme=h2c"
      - "traefik.http.routers.workadventure-room-api.tls=true"
      - "traefik.http.routers.workadventure-room-api.tls.certresolver=myresolver"
    restart: ${RESTART_POLICY}

  back:
    image: thecodingmachine/workadventure-back:${VERSION}
    environment:
      - PLAY_URL=https://${DOMAIN}
      - SECRET_JITSI_KEY
      - ENABLE_MAP_EDITOR
      - SECRET_KEY
      - ADMIN_API_TOKEN
      - ADMIN_API_URL
      - TURN_SERVER
      - TURN_USER
      - TURN_PASSWORD
      - TURN_STATIC_AUTH_SECRET
      - STUN_SERVER
      - JITSI_URL
      - JITSI_ISS
      - BBB_URL
      - BBB_SECRET
      - MAX_PER_GROUP
      - STORE_VARIABLES_FOR_LOCAL_MAPS
      - REDIS_HOST=workadventure_redis
      - PROMETHEUS_AUTHORIZATION_TOKEN
      - MAP_STORAGE_URL=map-storage:50053
      - INTERNAL_MAP_STORAGE_URL=http://map-storage:3000
      - PUBLIC_MAP_STORAGE_URL=https://${DOMAIN}/map-storage
      - PLAYER_VARIABLES_MAX_TTL
      - ENABLE_CHAT
      - ENABLE_CHAT_UPLOAD
      - SENTRY_DSN=${SENTRY_DSN_BACK}
      - SENTRY_RELEASE=${SENTRY_RELEASE}
      - SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE}
    networks:
      - traefik_network
      - workadventure_internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8nhub_traefik_network"
      - "traefik.http.middlewares.workadventure-strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.workadventure-back.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.workadventure-back.middlewares=workadventure-strip-api-prefix"
      - "traefik.http.routers.workadventure-back.entrypoints=websecure"
      - "traefik.http.routers.workadventure-back.tls=true"
      - "traefik.http.routers.workadventure-back.tls.certresolver=myresolver"
      - "traefik.http.routers.workadventure-back.service=workadventure-back"
      - "traefik.http.services.workadventure-back.loadbalancer.server.port=8080"
    restart: ${RESTART_POLICY}

  uploader:
    image: thecodingmachine/workadventure-uploader:${VERSION}
    environment:
      - UPLOADER_URL=https://${DOMAIN}/uploader
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_URL=${AWS_URL}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - REDIS_HOST=${UPLOADER_REDIS_HOST}
      - REDIS_PORT=${UPLOADER_REDIS_PORT}
      - ADMIN_API_URL=${ADMIN_API_URL}
      - ENABLE_CHAT_UPLOAD=${ENABLE_CHAT_UPLOAD}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}
    networks:
      - traefik_network
      - workadventure_internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8nhub_traefik_network"
      - "traefik.http.middlewares.workadventure-strip-uploader-prefix.stripprefix.prefixes=/uploader"
      - "traefik.http.routers.workadventure-uploader.rule=Host(`${DOMAIN}`) && PathPrefix(`/uploader`)"
      - "traefik.http.routers.workadventure-uploader.middlewares=workadventure-strip-uploader-prefix"
      - "traefik.http.routers.workadventure-uploader.entrypoints=websecure"
      - "traefik.http.routers.workadventure-uploader.tls=true"
      - "traefik.http.routers.workadventure-uploader.tls.certresolver=myresolver"
      - "traefik.http.routers.workadventure-uploader.service=workadventure-uploader"
      - "traefik.http.services.workadventure-uploader.loadbalancer.server.port=8080"
    restart: ${RESTART_POLICY}

  icon:
    image: matthiasluedtke/iconserver:v3.15.0
    networks:
      - traefik_network
      - workadventure_internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8nhub_traefik_network"
      - "traefik.http.middlewares.workadventure-strip-icon-prefix.stripprefix.prefixes=/icon"
      - "traefik.http.routers.workadventure-icon.middlewares=workadventure-strip-icon-prefix"
      - "traefik.http.routers.workadventure-icon.rule=Host(`${DOMAIN}`) && PathPrefix(`/icon`)"
      - "traefik.http.routers.workadventure-icon.entrypoints=websecure"
      - "traefik.http.routers.workadventure-icon.tls=true"
      - "traefik.http.routers.workadventure-icon.tls.certresolver=myresolver"
      - "traefik.http.routers.workadventure-icon.service=workadventure-icon"
      - "traefik.http.services.workadventure-icon.loadbalancer.server.port=8080"
    restart: ${RESTART_POLICY}

  # Redis renomeado para evitar conflito
  workadventure_redis:
    image: redis:6
    container_name: workadventure_redis
    volumes:
      - workadventure_redisdata:/data
    networks:
      - workadventure_internal
    restart: ${RESTART_POLICY}

  map-storage:
    image: thecodingmachine/workadventure-map-storage:${VERSION}
    environment:
      API_URL: back:50051
      PROMETHEUS_AUTHORIZATION_TOKEN: "$PROMETHEUS_AUTHORIZATION_TOKEN"
      AUTHENTICATION_STRATEGY: "$MAP_STORAGE_AUTHENTICATION_STRATEGY"
      ENABLE_BEARER_AUTHENTICATION: "$MAP_STORAGE_ENABLE_BEARER_AUTHENTICATION"
      ENABLE_BASIC_AUTHENTICATION: "$MAP_STORAGE_ENABLE_BASIC_AUTHENTICATION"
      ENABLE_DIGEST_AUTHENTICATION: "$MAP_STORAGE_ENABLE_DIGEST_AUTHENTICATION"
      AUTHENTICATION_USER: "$MAP_STORAGE_AUTHENTICATION_USER"
      AUTHENTICATION_PASSWORD: "$MAP_STORAGE_AUTHENTICATION_PASSWORD"
      AUTHENTICATION_TOKEN: "$MAP_STORAGE_AUTHENTICATION_TOKEN"
      AUTHENTICATION_VALIDATOR_URL: "$MAP_STORAGE_AUTHENTICATION_VALIDATOR_URL"
      SENTRY_DSN: $SENTRY_DSN_MAPSTORAGE
      SENTRY_RELEASE: $SENTRY_RELEASE
      SENTRY_ENVIRONMENT: $SENTRY_ENVIRONMENT
      SENTRY_TRACES_SAMPLE_RATE: $SENTRY_TRACES_SAMPLE_RATE
      SECRET_KEY: $SECRET_KEY
      PATH_PREFIX: "/map-storage"
      ENTITY_COLLECTION_URLS: "https://${DOMAIN}/collections/FurnitureCollection.json,https://${DOMAIN}/collections/OfficeCollection.json"
      MAP_STORAGE_API_TOKEN: "${MAP_STORAGE_API_TOKEN:-${SECRET_KEY}}"
      PUSHER_URL: "https://${DOMAIN}/"
    volumes:
      - workadventure_map_storage_data:/maps
    networks:
      - traefik_network
      - workadventure_internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8nhub_traefik_network"
      - "traefik.http.middlewares.workadventure-strip-map-storage-prefix.stripprefix.prefixes=/map-storage"
      - "traefik.http.routers.workadventure-map-storage.middlewares=workadventure-strip-map-storage-prefix"
      - "traefik.http.routers.workadventure-map-storage.rule=Host(`${DOMAIN}`) && PathPrefix(`/map-storage`)"
      - "traefik.http.routers.workadventure-map-storage.entrypoints=websecure"
      - "traefik.http.routers.workadventure-map-storage.tls=true"
      - "traefik.http.routers.workadventure-map-storage.tls.certresolver=myresolver"
      - "traefik.http.routers.workadventure-map-storage.service=workadventure-map-storage"
      - "traefik.http.services.workadventure-map-storage.loadbalancer.server.port=3000"
    restart: ${RESTART_POLICY}

  # Matrix Synapse
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: workadventure_synapse
    environment:
      - SYNAPSE_SERVER_NAME=${MATRIX_DOMAIN}
      - SYNAPSE_REPORT_STATS=yes
    volumes:
      - ./synapse/data:/data
    networks:
      - traefik_network
      - workadventure_internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8nhub_traefik_network"
      - "traefik.http.routers.workadventure-synapse.rule=Host(`${MATRIX_DOMAIN}`)"
      - "traefik.http.routers.workadventure-synapse.entrypoints=websecure"
      - "traefik.http.routers.workadventure-synapse.tls=true"
      - "traefik.http.routers.workadventure-synapse.tls.certresolver=myresolver"
      - "traefik.http.routers.workadventure-synapse.service=workadventure-synapse"
      - "traefik.http.services.workadventure-synapse.loadbalancer.server.port=8008"
    restart: ${RESTART_POLICY}

  

volumes:
  workadventure_redisdata:
  workadventure_map_storage_data:
